### ISSUE TITLE
ijgis_ca_carving does not build binaries

### ISSUE THREAD

**Issue by ninsbl** [vpmakinen/ijgis_ca_carving#1]
Thanks for this interesting tool! I am trying to get it installed, but the binaries do not seem to be build:
```
cmake ..
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   program_options
--   regex
--   system
-- GDAL found and working properly.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/NINA.NO/stefan.blumentrath/ijgis_ca_carving/build

$ ls -a bin
.  ..

```
This was on Ubunut 16.04 (with boost 1.58), but also Ubuntu 18.04 ( with boost 1.65) yields in the same result with an empty bin directory...

I also tested building with clang:
```
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
cmake ..
```
But this did not help either.

Any idea for how to get this running is welcome!

**Comment by ninsbl** [comment]
Tested now also on Fedora 29. Same result...

**Comment by frafra** [comment]
After `cmake` you need to run `make` :-)

If you use Fedora, here are the dependencies you need (tested on Fedora 30):

```
sudo dnf install make cmake gcc-c++ boost-devel gdal-devel
```
